config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  namespace :admin do
    get '/' => 'users#dashboard'

    resources :users do
      collection do
        get :dashboard
      end
    end

    resources :sessions do
      collection do
        get :login
        post :login_attempt
        get :logout
      end
    end

    resources :customer_accounts do
    end

    resources :orders
    resources :roles
    resources :permissions

    resources :divisions do
      collection do
        post :upload_division_image
      end
    end

    resources :sections do
      collection do
        post :upload_section_image
      end
    end

    resources :departments do
      collection do
        post :upload_department_image
      end
    end

    resources :items do
      collection do
        post :upload_item_image
      end
    end

    resources :offers do
      collection do
        post :upload_offer_image
      end
    end

  end
end

app/models/item.rb
class Item < ApplicationRecord
  belongs_to :section
  belongs_to :department
  belongs_to :division
  enum status: { active: 1, inactive: 2 }

end

app/controllers/admin/items_controller.rb
class Admin::ItemsController < ApiController
  before_action :authenticate_user

  def index
    @q = Item.includes(:section, :division, :department).ransack(params[:q])
    @items = @q.result.paginate(page: params[:page], per_page: 10)
  end

  def new
    @item = Item.new
  end

  def create
    @item = Item.new(cat_params)
    if @item.save
      set_flash_notification :success, :create, entity: ' Item'
      redirect_to admin_item_items_path
    else
      set_instant_flash_notification :danger, :default, {:message => @item.errors.messages[:base][0]}
      render :new
    end
  end

  def edit
    @item = Item.find(params[:id])
  end

  def update
    @item = Item.find(params[:id])
    if @item.update(cat_params)
      set_flash_notification :success, :update, entity: ' Item'
      redirect_to admin_item_items_path
    else
      set_instant_flash_notification :danger, :default, {:message => @item.errors.messages[:base][0]}
      render :edit
    end
  end

  def upload_item_image
    UploadToS3Service.new(params[:document], params[:barcode], {extension: 'jpg', public_read: true, upload_folder: "items"}).update_file
    set_flash_notification :success, :update, entity: ' Item'
    redirect_to admin_item_items_path
  end

  private

  def cat_params
    params.require(:item).permit(:division_id, :section_id, :department_id, :category, :company_name, :name, :mrp,
                                         :discount, :rsp, :standard_rate, :barcode, :item_hsn_description, :item_code, :item_hsn_code, :display, :status)
  end
end

app/helpers/items_helper.rb
module ItemsHelper
def categories_for_select
    ItemCategory.all.pluck(:name, :id).to_a
  end

  def subcategories_for_select
    ItemSubcategory.all.pluck( :name, :id).to_a
  end

  def items_for_select
    Item.includes(:item_category, :item_subcategory).all.collect{|item| ["#{item.name} (#{item.item_category.name}-#{item.item_subcategory.name})", item.id]}
  end
end

app/views/admin/items/_form.html.erb
<div class="col-xs-6 mt10">
  <%= f.label :division_id, 'Division' %>
  <%= f.select :division_id, Division.all.pluck(:name, :id), {include_blank: "--Division--"},
               { class: 'feedr-main-select form-control ','data-behavior' => "chosen-select", required: true} %>
</div>
<div class="col-xs-6 mt10">
  <%= f.label :section_id, 'Section' %>
  <%= f.select :section_id, Section.all.pluck(:name, :id), {include_blank: "--Section--"},
               { class: 'feedr-main-select form-control ','data-behavior' => "chosen-select", required: true}%>
</div>
<div class="col-xs-6 mt10">
  <%= f.label :department_id, 'Department' %>
  <%= f.select :department_id, Department.all.pluck(:name, :id), {include_blank: "--Department--"},
               { class: 'feedr-main-select form-control ','data-behavior' => "chosen-select", required: true}%>
</div>
<div class="col-xs-6 mt10">
  <%= f.label :category, 'Category' %>
  <%= f.text_field :category, class: 'form-control input feedr-main-input', required: true  %>
</div>
<div class="col-xs-6 mt10">
  <%= f.label :company_name, 'Company Name' %>
  <%= f.text_field :company_name, class: 'form-control input feedr-main-input', required: true  %>
</div>
<div class="col-xs-6 mt10">
  <%= f.label :name, 'Name' %>
  <%= f.text_field :name, class: 'form-control input feedr-main-input', required: true  %>
</div>
<div class="col-xs-6 mt10">
  <%= f.label :mrp, 'MRP' %>
  <%= f.text_field :mrp, class: 'form-control input feedr-main-input', required: true  %>
</div>
<div class="col-xs-6 mt10">
  <%= f.label :discount, 'Discount' %>
  <%= f.text_field :discount, class: 'form-control input feedr-main-input', required: true  %>
</div>
<div class="col-xs-6 mt10">
  <%= f.label :rsp, 'RSP' %>
  <%= f.text_field :rsp, class: 'form-control input feedr-main-input', required: true  %>
</div>
<div class="col-xs-6 mt10">
  <%= f.label :barcode, 'Barcode' %>
  <%= f.text_field :barcode, class: 'form-control input feedr-main-input', required: true  %>
</div>
<div class="col-xs-6 mt10">
  <%= f.label :item_code, 'Item Code' %>
  <%= f.text_field :item_code, class: 'form-control input feedr-main-input', required: true  %>
</div>

<div class="col-xs-6 mt10">
  <%= f.label :status, 'Status' %>
  <%= f.select :status, ['active', 'inactive'], {},
               { class: 'feedr-main-select form-control ','data-behavior' => "chosen-select", required: true}%>
</div>

app/views/admin/items/edit.html.erb
<div class="col-xs-12 no-left-pad">
  <div class="col-xs-5 no-left-pad">
    <h3>
      <%= link_to admin_items_path, class: "btn btn-blue" do %>
        Back
      <% end %>
    </h3>
  </div>
  <div class="col-xs-7">
    <h3> Item</h3>
  </div>
</div>
<div class="page-body">
  <div class="container-div row">
    <div class="panel panel-default">
      <div class="panel-body">
        <%= form_for(@item, :url => {:controller => 'admin/items', :action => 'update'}) do |f| %>
          <div class="row mrs mls new_form">
            <%= render 'form', f: f,form_type: "new" %>
          </div>
          <div class="row">
            <div class="col-md-12 mt10" align="right">
              <%= f.submit "Save", class: 'btn btn-green' %>
            </div>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>

<script>
    ChosenApplier.init($('select[data-behavior=chosen-select]'))
</script>

app/views/admin/items/index.html.erb
<div class="container-div page-body">

  <div class="col-xs-12">
    <div class="col-xs-5 no-left-pad">
      <h3>
        <%= link_to new_admin_item_path, class: "btn btn-green" do %>
          Add Items
        <% end %>
      </h3>
    </div>
    <div class="col-xs-7">
      <h3> Item</h3>
    </div>
  </div>

  <div class="col-xs-12 mt10">
    <%= search_form_for(@q,url: admin_items_path, id: 'item_search_form') do |f| %>
      <div class="col-xs-2 no-left-pad">
        <%= f.label :division_id_eq, 'Division' %>
        <%= f.select :division_id_eq, Division.all.pluck(:name, :id), {include_blank: "--Division--"},
                     { class: 'feedr-main-select form-control ','data-behavior' => "chosen-select"} %>
      </div>
      <div class="col-xs-2 no-left-pad">
        <%= f.label :section_id_eq, 'Section' %>
          <%= f.select :section_id_eq, Section.all.pluck(:name, :id), {include_blank: "--Section--"},
                       { class: 'feedr-main-select form-control ','data-behavior' => "chosen-select"}%>
      </div>
      <div class="col-xs-2 no-left-pad">
        <%= f.label :department_id_eq, 'Department' %>
        <%= f.select :department_id_eq, Department.all.pluck(:name, :id), {include_blank: "--Department--"},
                     { class: 'feedr-main-select form-control ','data-behavior' => "chosen-select"}%>
      </div>
      <div class="col-xs-2 no-left-pad">
        <%= f.label :company_name_cont, 'Company Name' %>
        <%=f.text_field :company_name_cont, class: 'form-control feedr-main-input'%>
      </div>
      <div class="col-xs-2 no-left-pad">
        <%= f.label :name_cont, 'Item Name' %>
        <%=f.text_field :name_cont, class: 'form-control feedr-main-input'%>
      </div>
      <div class="col-xs-2 pt20" align="right">
        <%=f.submit 'Search', class: 'form-control btn-green'%>
      </div>
    <%end%>
  </div>


  <div class="col-xs-12 mt10">
    <table class="table table-bordered table-striped feedr-main-tabl" >
      <thead>
      <tr>
        <th class="col-xs-1">Id</th>
        <th class="col-xs-1">Division</th>
        <th class="col-xs-1">Section</th>
        <th class="col-xs-1">Department</th>
        <th class="col-xs-1">Company Name</th>
        <th class="col-xs-2">Name</th>
        <th class="col-xs-1">MRP</th>
        <th class="col-xs-1">RSP</th>
        <th class="col-xs-1">Status</th>
        <th class="col-xs-3">Action</th>
      </tr>
      </thead>
      <tbody>
      <% @items.each do |item| %>
        <tr>
          <td><%= item.id%></td>
          <td><%= item.division.try(:name)%></td>
          <td><%= item.section.try(:name)%></td>
          <td><%= item.department.try(:name)%></td>
          <td><%= item.company_name%></td>
          <td><%= item.name%></td>
          <td><%= item.mrp%></td>
          <td><%= item.rsp%></td>
          <td><%= item.status%></td>
          <td>
            <div>
              <div class="col-xs-12">
                <%= link_to edit_admin_item_path(item), class: "btn btn-sm btn-blue" do %>
                  Edit
                <% end %>
              </div>
              <div class="col-xs-8 mt10">
                <%= image_tag "https://s3-ap-southeast-1.amazonaws.com/feedr./items/#{item.barcode}.jpg", width: '60px', id: "upload", class: "pointer" %>
              </div>
              <div class="col-xs-4 pt32">
                <%= form_tag upload_item_image_admin_items_path(barcode: item.barcode), class: 'form-horizontal', id: 'upload_form', multipart: true do |f| %>
                  <label for="document"><%= image_tag 'upload_image.svg', width: '30px', id: "upload", class: "pointer" %></label>
                  <%= file_field_tag :document, class: 'mechanic_file', style:"display: none" %>
                <% end %>
              </div>
            </div>
          </td>
        </tr>
      <% end %>
      </tbody>
    </table>
    <div class="page_links ppl">
      <%= will_paginate @items%>
    </div>
  </div>
</div>

<script>
    $('#document').change(function(){
        $('#upload_form').submit()
    });
</script>

app/views/admin/items/new.html.erb
<div class="col-xs-12 no-left-pad">
  <div class="col-xs-5 no-left-pad">
    <h3>
      <%= link_to admin_items_path, class: "btn btn-blue" do %>
        Back
      <% end %>
    </h3>
  </div>
  <div class="col-xs-7">
    <h3> Item</h3>
  </div>
</div>
<div class="page-body">
  <div class="container-div row">
    <div class="panel panel-default">
      <div class="panel-body">
        <%= form_for(@item, :url => {:controller => 'admin/items', :action => 'create'}) do |f| %>
          <div class="row mrs mls new_form">
            <%= render 'form', f: f,form_type: "new" %>
          </div>
          <div class="row">
            <div class="col-md-12 mt10" align="right">
              <%= f.submit "Add", class: 'btn btn-green' %>
            </div>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>
<script>
    ChosenApplier.init($('select[data-behavior=chosen-select]'))
</script>