config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  namespace :admin do
    get '/' => 'users#dashboard'

    resources :users do
      collection do
        get :dashboard
      end
    end

    resources :sessions do
      collection do
        get :login
        post :login_attempt
        get :logout
      end
    end

    resources :customer_accounts do
    end

    resources :orders
    resources :roles
    resources :permissions

    resources :divisions do
      collection do
        post :upload_division_image
      end
    end

    resources :sections do
      collection do
        post :upload_section_image
      end
    end

    resources :departments do
      collection do
        post :upload_department_image
      end
    end

    resources :items do
      collection do
        post :upload_item_image
      end
    end

    resources :offers do
      collection do
        post :upload_offer_image
      end
    end

  end
end

app/models/section.rb
class Section < ApplicationRecord
  has_many :items
  enum status: { active: 1, inactive: 2 }
end

app/controllers/admin/sections_controller.rb
class Admin::SectionsController < ApiController
  before_action :authenticate_user

  def index
    @q = Section.ransack(params[:q])
    @sections = @q.result.paginate(page: params[:page], per_page: 10)
  end

  def new
    @section = Section.new
  end

  def create
    @section = Section.new(cat_params)
    if @section.save
      set_flash_notification :success, :create, entity: ' Section'
      redirect_to admin_sections_path
    else
      set_instant_flash_notification :danger, :default, {:message => @section.errors.messages[:base][0]}
      render :new
    end
  end

  def edit
    @section = Section.find(params[:id])
  end

  def update
    @section = Section.find(params[:id])
    if @section.update(cat_params)
      set_flash_notification :success, :update, entity: ' Section'
      redirect_to admin_sections_path
    else
      set_instant_flash_notification :danger, :default, {:message => @section.errors.messages[:base][0]}
      render :edit
    end
  end

  def upload_section_image
    UploadToS3Service.new(params[:document], params[:id], {extension: 'jpg', public_read: true, upload_folder: "sections"}).update_file
    set_flash_notification :success, :update, entity: ' Section'
    redirect_to admin_sections_path
  end

  private

  def cat_params
    params.require(:section).permit(:name,:status)
  end
end

app/views/admin/sections/edit.html.erb
<div class="container-div page-body">
  <div>
    <div class="col-xs-12" align="center">
      <h3> sections</h3>
    </div>
    <div class="col-xs-12">
      <div class="col-md-2 col-md-offset-2">
        <h3>
          <%= link_to admin_sections_path, class: "btn btn-blue" do %>
            Back
          <% end %>
        </h3>
      </div>
    </div>
  </div>

  <div class="col-xs-8 col-xs-offset-2">
    <table class="table table-bordered table-striped table-hover table-data table-overview display" >
      <thead>
      <tr>
        <th class="col-xs-1">Id</th>
        <th class="col-xs-8">Name</th>
        <th class="col-xs-3">Action</th>
      </tr>
      </thead>
      <tbody>
      <% Section.all.each do |section| %>
        <tr>
          <td><%= section.id%></td>
          <%if section.id == @section.id %>
            <%= form_for @section, url: admin_section_path do |f| %>
              <td><%= f.text_field :name, class: 'form-control feedr-main-input input', required: true %></td>
              <td>
                <%= f.submit "Update", class: 'btn btn-green' %>
              </td>
            <% end %>
          <% else %>
            <td><%= section.name%></td>
            <td>
            </td>
          <% end %>
        </tr>
      <% end %>
      </tbody>
    </table>
    <div class="page_links ppl">
      <%#= will_paginate @locations%>
    </div>
  </div>
</div>

app/views/admin/sections/index.html.erb
<div class="container-div page-body">
  <div>
    <div class="col-xs-12" align="center">
      <h3>Sections</h3>
    </div>
    <div class="col-xs-12 no-left-pad">
      <div class="col-md-2 col-md-offset-2 ">
        <h3>
          <%= link_to new_admin_section_path, class: "btn btn-green" do %>
            Add
          <% end %>
        </h3>
      </div>
    </div>
  </div>

  <div class="col-xs-8 col-xs-offset-2">
    <table class="table table-bordered table-striped feedr-main-tabl" >
      <thead>
      <tr>
        <th class="col-xs-1">Id</th>
        <th class="col-xs-5">Name</th>
        <th class="col-xs-1">Status</th>
        <th class="col-xs-4">Action</th>
      </tr>
      </thead>
      <tbody>
      <% @sections.each do |section| %>
        <tr>
          <td><%= section.id%></td>
          <td><%= section.name%></td>
          <% if section.status=='active' %>
            <td class="status-active" ><%= section.status%></td>
          <% else %>
            <td class="status-inactive" ><%= section.status%></td>
          <%end %>
          <td>
            <div>
              <div class="col-xs-4">
                <%= link_to edit_admin_section_path(section), class: "btn btn-sm btn-blue" do %>
                  Edit
                <% end %>
              </div>
              <div class="col-xs-4">
                <%= image_tag "https://s3-ap-southeast-1.amazonaws.com/feedr/sections/#{section.id}.jpg", width: '60px', id: "upload", class: "pointer" %>

              </div>
              <div class="col-xs-4">
                <%= form_tag upload_section_image_admin_sections_path(id: section.id), class: 'form-horizontal', id: 'upload_form', multipart: true do |f| %>
                  <label for="document"><%= image_tag 'upload_image.svg', width: '30px', id: "upload", class: "pointer" %></label>
                  <%= file_field_tag :document, class: 'mechanic_file', style:"display: none" %>
                <% end %>
              </div>
            </div>
          </td>
        </tr>
      <% end %>
      </tbody>
    </table>
    <div class="page_links ppl">
      <%= will_paginate @sections%>
    </div>
  </div>
</div>

<script>
    $('#document').change(function(){
        $('#upload_form').submit()
    });
</script>

app/views/admin/sections/new.html.erb
<div class="container-div page-body">
  <div>
    <div class="col-xs-12" align="center">
      <h3> sections</h3>
    </div>
    <div class="col-xs-12 no-left-pad">
      <div class="col-md-2 col-md-offset-2">
        <h3>
          <%= link_to admin_sections_path, class: "btn btn-blue" do %>
             Back
          <% end %>
        </h3>
      </div>
    </div>
  </div>

  <div class="col-xs-8 col-xs-offset-2">
    <table class="table table-bordered table-striped" >
      <thead>
      <tr>
        <th class="col-xs-1">Id</th>
        <th class="col-xs-6">Name</th>
        <th class="col-xs-2">Status</th>
        <th class="col-xs-3">Action</th>
      </tr>
      </thead>
      <tbody>
      <tr>
        <td></td>
        <%= form_for @section, url: admin_sections_path do |f| %>
          <td><%= f.text_field :name, class: 'form-control input feedr-main-input', required: true %></td>
          <td>
            <%= f.select :status, ['active', 'inactive'], {include_blank: "Status"},
                         { class: 'feedr-main-select form-control ','data-behavior' => "chosen-select", required: true}%>
          </td>
          <td>
            <%= f.submit "Save", class: 'btn btn-green' %>
          </td>
        <% end %>
      </tr>
      <% Section.all.each do |section| %>
        <tr>
          <td><%= section.id%></td>
          <td><%= section.name%></td>
          <td><%= section.status%></td>
          <td>
          </td>
        </tr>
      <% end %>
      </tbody>
    </table>
    <div class="page_links ppl">
      <%#= will_paginate @locations%>
    </div>
  </div>
</div>