config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  namespace :admin do
    get '/' => 'users#dashboard'

    resources :users do
      collection do
        get :dashboard
      end
    end

    resources :sessions do
      collection do
        get :login
        post :login_attempt
        get :logout
      end
    end

    resources :customer_accounts do
    end

    resources :orders
    resources :roles
    resources :permissions

    resources :divisions do
      collection do
        post :upload_division_image
      end
    end

    resources :sections do
      collection do
        post :upload_section_image
      end
    end

    resources :departments do
      collection do
        post :upload_department_image
      end
    end

    resources :items do
      collection do
        post :upload_item_image
      end
    end

    resources :offers do
      collection do
        post :upload_offer_image
      end
    end

  end
end

app/models/division.rb
class Division < ApplicationRecord
  has_many :items
  enum status: { active: 1, inactive: 2 }
end

app/controllers/admin/divisions_controller.rb
class Admin::DivisionsController < ApiController
  before_action :authenticate_user

  def index
    @q = Division.ransack(params[:q])
    @divisions = @q.result.paginate(page: params[:page], per_page: 10)
  end

  def new
    @division = Division.new
  end

  def create
    @division = Division.new(div_params)
    if @division.save
      set_flash_notification :success, :create, entity: 'Division'
      redirect_to admin_divisions_path
    else
      set_instant_flash_notification :danger, :default, {:message => @division.errors.messages[:base][0]}
      render :new
    end
  end

  def edit
    @division = Division.find(params[:id])
  end

  def update
    @division = Division.find(params[:id])
    if @division.update(div_params)
      set_flash_notification :success, :update, entity: 'Division'
      redirect_to admin_divisions_path
    else
      set_instant_flash_notification :danger, :default, {:message => @division.errors.messages[:base][0]}
      render :edit
    end
  end

  def upload_division_image
    UploadToS3Service.new(params[:document], params[:id], {extension: 'jpg', public_read: true, upload_folder: "divisions"}).update_file
    set_flash_notification :success, :update, entity: 'Division'
    redirect_to admin_divisions_path
  end

  private

  def div_params
    params.require(:division).permit(:name,:status)
  end
end

app/views/admin/divisions/edit.html.erb
<div class="container-div page-body">
  <div>
    <div class="col-xs-12" align="center">
      <h3> Divisions</h3>
    </div>
    <div class="col-xs-12">
      <div class="col-md-2 col-md-offset-2">
        <h3>
          <%= link_to admin_divisions_path, class: "btn btn-blue" do %>
            Back
          <% end %>
        </h3>
      </div>
    </div>
  </div>

  <div class="col-xs-8 col-xs-offset-2">
    <table class="table table-bordered table-striped table-hover table-data table-overview display" >
      <thead>
      <tr>
        <th class="col-xs-1">Id</th>
        <th class="col-xs-8">Name</th>
        <th class="col-xs-3">Action</th>
      </tr>
      </thead>
      <tbody>
      <% Division.all.each do |division| %>
        <tr>
          <td><%= division.id%></td>
          <%if division.id == @division.id %>
            <%= form_for @division, url: admin_division_path do |f| %>
              <td><%= f.text_field :name, class: 'form-control feedr-main-input input', required: true %></td>
              <td>
                <%= f.submit "Update", class: 'btn btn-green' %>
              </td>
            <% end %>
          <% else %>
            <td><%= division.name%></td>
            <td>
            </td>
          <% end %>
        </tr>
      <% end %>
      </tbody>
    </table>
    <div class="page_links ppl">
      <%#= will_paginate @locations%>
    </div>
  </div>
</div>

app/views/admin/divisions/index.html.erb
<div class="container-div page-body">
  <div>
    <div class="col-xs-12" align="center">
      <h3>Divisions</h3>
    </div>
    <div class="col-xs-12 no-left-pad">
      <div class="col-md-2 col-md-offset-2 ">
        <h3>
          <%= link_to new_admin_division_path, class: "btn btn-green" do %>
            Add
          <% end %>
        </h3>
      </div>
    </div>
  </div>

  <div class="col-xs-8 col-xs-offset-2">
    <table class="table table-bordered table-striped feedr-main-tabl" >
      <thead>
      <tr>
        <th class="col-xs-1">Id</th>
        <th class="col-xs-5">Name</th>
        <th class="col-xs-1">Status</th>
        <th class="col-xs-4">Action</th>
      </tr>
      </thead>
      <tbody>
      <% @divisions.each do |division| %>
        <tr>
          <td><%= division.id%></td>
          <td><%= division.name%></td>
          <% if division.status=='active' %>
            <td class="status-active" ><%= division.status%></td>
          <% else %>
            <td class="status-inactive" ><%= division.status%></td>
          <%end %>
          <td>
            <div>
              <div class="col-xs-4">
                <%= link_to edit_admin_division_path(division), class: "btn btn-sm btn-blue" do %>
                  Edit
                <% end %>
              </div>
              <div class="col-xs-4">
                <%= image_tag "https://s3-ap-southeast-1.amazonaws.com/b2b/divisions/#{division.id}.jpg", width: '60px', id: "upload", class: "pointer" %>

              </div>
              <div class="col-xs-4">
                <%= form_tag upload_division_image_admin_divisions_path(id: division.id), class: 'form-horizontal', id: 'upload_form', multipart: true do |f| %>
                  <label for="document"><%= image_tag 'upload_image.svg', width: '30px', id: "upload", class: "pointer" %></label>
                  <%= file_field_tag :document, class: 'mechanic_file', style:"display: none" %>
                <% end %>
              </div>
            </div>
          </td>
        </tr>
      <% end %>
      </tbody>
    </table>
    <div class="page_links ppl">
      <%= will_paginate @divisions%>
    </div>
  </div>
</div>

<script>
    $('#document').change(function(){
        $('#upload_form').submit()
    });
</script>

app/views/admin/divisions/new.html.erb
<div class="container-div page-body">
  <div>
    <div class="col-xs-12" align="center">
      <h3> Divisions</h3>
    </div>
    <div class="col-xs-12 no-left-pad">
      <div class="col-md-2 col-md-offset-2">
        <h3>
          <%= link_to admin_divisions_path, class: "btn btn-blue" do %>
             Back
          <% end %>
        </h3>
      </div>
    </div>
  </div>

  <div class="col-xs-8 col-xs-offset-2">
    <table class="table table-bordered table-striped" >
      <thead>
      <tr>
        <th class="col-xs-1">Id</th>
        <th class="col-xs-6">Name</th>
        <th class="col-xs-2">Status</th>
        <th class="col-xs-3">Action</th>
      </tr>
      </thead>
      <tbody>
      <tr>
        <td></td>
        <%= form_for @division, url: admin_divisions_path do |f| %>
          <td><%= f.text_field :name, class: 'form-control input feedr-main-input', required: true %></td>
          <td>
            <%= f.select :status, ['active', 'inactive'], {include_blank: "Status"},
                         { class: 'feedr-main-select form-control ','data-behavior' => "chosen-select", required: true}%>
          </td>
          <td>
            <%= f.submit "Save", class: 'btn btn-green' %>
          </td>
        <% end %>
      </tr>
      <% Division.all.each do |division| %>
        <tr>
          <td><%= division.id%></td>
          <td><%= division.name%></td>
          <td><%= division.status%></td>
          <td>
          </td>
        </tr>
      <% end %>
      </tbody>
    </table>
    <div class="page_links ppl">
      <%#= will_paginate @locations%>
    </div>
  </div>
</div>